## Request to take a picture at a specified position

# Position is expected in MTM-7 with ellipsoid height
# Orientation is a quaternion relative to the ENU frame
geometry_msgs/Pose target_pose

---
# RESULT DEFINITION

std_msgs/UInt32 result_status
grid_map_msgs/GridMap costmap

---
# FEEDBACK DEFINITION

std_msgs/UInt32 feedback_status

