<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>any_msgs</name>
  <version>0.6.24</version>
  <description>Collection of commonly used ROS messages and services, vendored (ROS1) from ANYbotics' any_msgs -- anymal_msgs' own dependency.</description>
  <maintainer email="william.fecteau@norlab.ulaval.ca">William Fecteau</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>message_generation</build_depend>
  <exec_depend>message_runtime</exec_depend>

  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
</package>
